# Generated by Django 5.2 on 2025-06-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='terms_agreed',
            field=models.BooleanField(default=False),
        ),
    ]
